### ISSUE TITLE
代理服务器确定可用的情况下，代理服务是需要验证的

### ISSUE THREAD

**Issue by CoffinLove** [yuezk/chatgpt-mirror#6]
FetchError: request to https://api.openai.com/v1/chat/completions failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (file:///chatgpt-mirror/node_modules/isomorphic-unfetch/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:525:35)
    at onerror (/chatgpt-mirror/node_modules/agent-base/src/index.ts:236:9)
    at callbackError (/chatgpt-mirror/node_modules/agent-base/src/index.ts:258:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by yuezk** [comment]
用的 socks5 代理，还是 http 代理？

**Comment by CoffinLove** [comment]
http和socket都开着，curl --proxy https://xxx:xxxx@192.168.1.2:7890 --insecure https://www.google.com，测试代理是通过的

**Comment by CoffinLove** [comment]
我取消了验证后还是不行，我rm在pull一下吧，代理的格式是什么

/chatgpt-mirror/node_modules/proxy-agent/index.js:112
    throw new TypeError('unsupported proxy protocol: "' + protocol + '"');
          ^
TypeError: unsupported proxy protocol: "192.168.1.2"
    at mapOptsToProxy (/chatgpt-mirror/node_modules/proxy-agent/index.js:112:11)
    at new ProxyAgent (/chatgpt-mirror/node_modules/proxy-agent/index.js:150:17)
    at fetch (file:///chatgpt-mirror/src/chatgpt.service.ts:24:31)
    at fetchSSE (file:///chatgpt-mirror/node_modules/chatgpt/src/fetch-sse.ts:13:21)
    at file:///chatgpt-mirror/node_modules/chatgpt/src/chatgpt-api.ts:190:11
    at new Promise (<anonymous>)
    at ChatGPTAPI.sendMessage (file:///chatgpt-mirror/node_modules/chatgpt/src/chatgpt-api.ts:171:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by yuezk** [comment]
我测试了我本地的 http://127.0.0.1:1087 和 socks5://127.0.0.1:1086 是可以的

**Comment by yuezk** [comment]
你的代理服务器本身也需要 auth?

**Comment by CoffinLove** [comment]
感谢作者，我是对代理服务我本身加了验证，取消验证后按照这样的格式http://192.168.1.2:port，可用，希望可以支持能加验证的代理，https这样可能更安全。。。

**Comment by yuezk** [comment]
@CoffinLove 好的，晚些时候加上

**Comment by yuezk** [comment]
@CoffinLove 如果需要 authentication 的话，可以配置成 `HTTP_PROXY=http://user:pass@127.0.0.1:1087`，socks 代理也一样。

**Comment by CoffinLove** [comment]
我抓包看了下，这个模型是自动的？不是固定GTP-3-T？
![image](https://user-images.githubusercontent.com/39045932/223321694-9e7f90ff-82a9-47d9-b30d-85c9feadfb43.png)

**Comment by yuezk** [comment]
这个项目的前端部分只是保存的官网的静态页面而已，并没有作太多修改，也没有办法改。这个项目偷梁换柱把接口给反代了，所以并不关心前端传的模型参数，后端接口默认使用 gpt-3.5-turbo 的模型

**Comment by CoffinLove** [comment]
原来如此
